* AudioTextSync To Ren’Py
Turn any of your [[https://github.com/kanjieater/SubPlz][SubPlz]] subtitle files + audio + epub combo into a visual novel, thanks to Ren’Py, with all advantages that come with it like (not exhaustive or exclusive to VNs):
- Saving!
- Loading!!!
- Play the audiobook at your own pace
- Replaying line audio
- Rollback/Skipping text
- Furigana
- Background / Text styling
- No overwhelmingly long paragraphs (inspired by [[https://app.readwok.com/lib][readwok]] on that one)
- Free shot of dopamine every time you click to the next line, keeping your tiktok-corroded brain active and focused on the book
- Clipboard Sync by design, no need to bother with textractor
- [[https://sync.renpy.org/][Share save accross computers?]]
- Images integration from the epub file (experimental !!)
Note that many of these things can be achieved with mpv+extensions+shortcuts if you prefer that way.

* How To Use
All instructions can now be found [[https://www.asayake.xyz/posts/audiobooksync/][here]]
* Status
Thanks to the improvements in the newer versions of SubPlz, this is essentially close to a complete release now, some things are left to more experimentation (like inserting images from epub), but aside from that results are now very accurate.
* Building
Assuming rust installed. If not, install it via [[https://rustup.rs/][Rustup]], then:

Make sure you have GTK installed as well.
#+begin_src bash
cargo build --release
#+end_src

